/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Televisor;

import javax.swing.JLabel;
import javax.swing.JProgressBar;

/**
 *
 * @author jprod
 */
public class FrmTelevisor extends javax.swing.JFrame {

    private ControladorTelevisor controlador;
    
    public JLabel getLblCanal() {
        return lblCanal;
    }

    public JLabel getLblPantalla() {
        return lblPantalla;
    }

    public JProgressBar getPgbVBC() {
        return pgbVBC;
    }
    
    /**
     * Creates new form FrmTelevisor
     */
    public FrmTelevisor() {
        initComponents();
        //this.lblCanal.setVisible(false);
        //this.pgbVBC.setVisible(false);
        
        controlador=new ControladorTelevisor(this,new Televisor());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCanal = new javax.swing.JLabel();
        pgbVBC = new javax.swing.JProgressBar();
        btnOnOFF = new javax.swing.JToggleButton();
        btnBajarViolumen = new javax.swing.JButton();
        btnSubirCanal = new javax.swing.JButton();
        btnBajarrCanal = new javax.swing.JButton();
        btnSubirVolumen = new javax.swing.JButton();
        lblPantalla = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblCanal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(lblCanal);
        lblCanal.setBounds(398, 28, 56, 28);

        pgbVBC.setOrientation(1);
        pgbVBC.setString("0 %");
        pgbVBC.setStringPainted(true);
        getContentPane().add(pgbVBC);
        pgbVBC.setBounds(434, 70, 14, 196);

        btnOnOFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnOFFActionPerformed(evt);
            }
        });
        getContentPane().add(btnOnOFF);
        btnOnOFF.setBounds(420, 280, 42, 14);

        btnBajarViolumen.setText("+");
        getContentPane().add(btnBajarViolumen);
        btnBajarViolumen.setBounds(196, 280, 42, 14);

        btnSubirCanal.setText("+");
        getContentPane().add(btnSubirCanal);
        btnSubirCanal.setBounds(364, 280, 42, 14);

        btnBajarrCanal.setText("+");
        getContentPane().add(btnBajarrCanal);
        btnBajarrCanal.setBounds(308, 280, 42, 14);

        btnSubirVolumen.setText("+");
        getContentPane().add(btnSubirVolumen);
        btnSubirVolumen.setBounds(252, 280, 42, 14);

        lblPantalla.setBackground(new java.awt.Color(51, 51, 51));
        lblPantalla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPantalla.setOpaque(true);
        getContentPane().add(lblPantalla);
        lblPantalla.setBounds(14, 14, 448, 258);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pantalla-tactil-de-75-4k-promethean-activpanel-nickel-android-8-0030502.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-14, 0, 500, 319);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOnOFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnOFFActionPerformed
        controlador.power();
    }//GEN-LAST:event_btnOnOFFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTelevisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTelevisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTelevisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTelevisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTelevisor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBajarViolumen;
    private javax.swing.JButton btnBajarrCanal;
    private javax.swing.JToggleButton btnOnOFF;
    private javax.swing.JButton btnSubirCanal;
    private javax.swing.JButton btnSubirVolumen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCanal;
    private javax.swing.JLabel lblPantalla;
    private javax.swing.JProgressBar pgbVBC;
    // End of variables declaration//GEN-END:variables
}
